// AUTO-GENERATED by scripts/generate-media.mjs — run `npm run media` to refresh.
// Add or remove files in public/images and public/videos, then regenerate.
// Captions and titles can be overridden in data/media-captions.ts.

import type { DerivedPhoto, MediaMonth } from "./media-types";

export const mediaMonths: MediaMonth[] = [
  {
    "key": "2025-08",
    "label": "August 2025",
    "age": "The very first days",
    "photos": [
      {
        "id": "photo-1000025855-jpg",
        "src": "/media/1000025855-jpg.webp",
        "date": "2025-08-28",
        "caption": "28 August 2025",
        "alt": "Photo from 28 August 2025",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdMoCGACJQCAbcgLlG1gAAySCBCxWNCL+srF691N7ajrco+SA5Jgs5D8meUS1UOdNPx8vNX9CslqCUPbgHN6lufsBNpZuglmgvyovHZW2/f2aOey/z2j2b0mlbfPIWi7BxI1xMWdmzZAAAAA=="
      },
      {
        "id": "photo-1000027361-jpg",
        "src": "/media/1000027361-jpg.webp",
        "date": "2025-08-31",
        "caption": "31 August 2025",
        "alt": "Photo from 31 August 2025",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCsH8I/+AUAjMx+SUyjWkIAAPkSSl1dLgzEJXw8JCgYJ9Xc98pw3qjp8uezbIYSjmEbkZPbA3scKVv7gn37PdnE6Jep6dbLeSgBdrcVmo+3NCsfw96lnCloJtdVCj7hBqr+LGUHQG1gxSNpWEomozK0fg9tkezOGQAA"
      }
    ],
    "videos": []
  },
  {
    "key": "2025-09",
    "label": "September 2025",
    "age": "1 month old",
    "photos": [
      {
        "id": "photo-1000034978-jpg",
        "src": "/media/1000034978-jpg.webp",
        "date": "2025-09-13",
        "caption": "13 September 2025",
        "alt": "Photo from 13 September 2025",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoCGACCckjBVRlBoNTPKVUQAAPeza3uQ1J9S8Ao/Bh9lvvJmkRKll2xklU/zwR1J5HDxwWRvEEIzemFJ2caLdmzn7Q1wVx1shQTW/Bk5t3r6a5YP+qm5vtWlqfwJKufPYSImVqC6jJbz1IE2RXtOpiAA"
      },
      {
        "id": "photo-1000041462-jpg",
        "src": "/media/1000041462-jpg.webp",
        "date": "2025-09-23",
        "caption": "23 September 2025",
        "alt": "Photo from 23 September 2025",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdAB6WV4rv1jBS2t+RD2gA/rsKRJ6ozZXqb3STR7Y8M5ECv4Ifq7O6csbx74m525WK8/ugghDSVP4tOWMHsr7Z3zyP6MK2cFF1ZEuZ438uBv/HkXhm+vcXiHPsisCgzCrAAAA="
      }
    ],
    "videos": []
  },
  {
    "key": "2025-10",
    "label": "October 2025",
    "age": "2 months old",
    "photos": [],
    "videos": [
      {
        "id": "video-vid20251005200421",
        "src": "/videos/VID20251005200421.mp4",
        "date": "2025-10-05",
        "title": "October 2025 clip 1",
        "description": "Recorded on 5 October 2025",
        "poster": "/media/1000025855-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdMoCGACJQCAbcgLlG1gAAySCBCxWNCL+srF691N7ajrco+SA5Jgs5D8meUS1UOdNPx8vNX9CslqCUPbgHN6lufsBNpZuglmgvyovHZW2/f2aOey/z2j2b0mlbfPIWi7BxI1xMWdmzZAAAAA=="
      }
    ]
  },
  {
    "key": "2026-01",
    "label": "January 2026",
    "age": "5 months old",
    "photos": [
      {
        "id": "photo-1000121345-jpg",
        "src": "/media/1000121345-jpg.webp",
        "date": "2026-01-02",
        "caption": "2 January 2026",
        "alt": "Photo from 2 January 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdMoMpADL+sQI5+VJBo0UAAP7vBC3hLlNx/kvA3kW86tB/Fld1qeNi+BVGCeum4FqAJjzZq7fGJc0hmRlY6BsdT+RJEKMIGLUtG4RkKHKo+rEbAgFUTo4d3bdTYUJNlOkJXghfv3eQQIQKJgYybcMWwYh4AAA="
      },
      {
        "id": "photo-1000140329-jpg",
        "src": "/media/1000140329-jpg.webp",
        "date": "2026-01-31",
        "caption": "31 January 2026",
        "alt": "Photo from 31 January 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCsABd5oHZW1w934AD+sQIsd2rK4W9ybtO2SR1GNd1mFQeJYf/MlmmrAGzyFZdNtNblL0xvmnHhokx6gQlcY36xJkRY1gaISFI+OzENOXVj/P/7RDv1CNnjAK3IoAA="
      }
    ],
    "videos": [
      {
        "id": "video-vid20260131153603",
        "src": "/videos/VID20260131153603.mp4",
        "date": "2026-01-31",
        "title": "January 2026 clip 1",
        "description": "Recorded on 31 January 2026",
        "poster": "/media/1000121345-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdMoMpADL+sQI5+VJBo0UAAP7vBC3hLlNx/kvA3kW86tB/Fld1qeNi+BVGCeum4FqAJjzZq7fGJc0hmRlY6BsdT+RJEKMIGLUtG4RkKHKo+rEbAgFUTo4d3bdTYUJNlOkJXghfv3eQQIQKJgYybcMWwYh4AAA="
      }
    ]
  },
  {
    "key": "2026-02",
    "label": "February 2026",
    "age": "6 months old",
    "photos": [
      {
        "id": "photo-1000142460-jpg",
        "src": "/media/1000142460-jpg.webp",
        "date": "2026-02-03",
        "caption": "3 February 2026",
        "alt": "Photo from 3 February 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoMpHY5AKni0/EThO5iAAP4CdigtGX1HJtJ8TIUTNyXupqhvNIB5qbBFaOr6BAa9JadgxDP1nwn7P3E5pxKthB5TI8ZI+W5n9FzlNiJ/6K1g/tOw+4OiezS2WBYcxnu4H++w7TviJz7i2DHZWmeMTFIfx6kCvyh0KgHul/3jvrtjI2heI4t5FaeXeYOLUbNGSYAqoAAA"
      }
    ],
    "videos": []
  },
  {
    "key": "2026-03",
    "label": "March 2026",
    "age": "7 months old",
    "photos": [
      {
        "id": "photo-1000171143-jpg",
        "src": "/media/1000171143-jpg.webp",
        "date": "2026-03-18",
        "caption": "18 March 2026",
        "alt": "Photo from 18 March 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgZYAltNVAEFJrSfqzt8AA+NDxV4PhS9fvcNjzzqfn7JPyNPXS2zsWmaSMAr0Rkv9GJ0E9rRtIe6GlmwaqF54knRMkx72eyGV7wNZ9HWbeZ1gD5hMceGMuyAAA"
      },
      {
        "id": "photo-1000175489-jpg",
        "src": "/media/1000175489-jpg.webp",
        "date": "2026-03-25",
        "caption": "25 March 2026",
        "alt": "Photo from 25 March 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQAHOAFYMwCHotxCQpvBHqwAA/hd4O+Z5Bj8MflpZ6cSJR1MKYZOu1Sv9F2jOPyLDKZzM3058UlnlKEFpVzjkc+5P4IDZPzl95wEj5jYNwlgPHd1HFTMmKFG/FYLTXU0vjas9TTAAAA=="
      }
    ],
    "videos": [
      {
        "id": "video-vid20260301195902",
        "src": "/videos/VID20260301195902.mp4",
        "date": "2026-03-01",
        "title": "March 2026 clip 1",
        "description": "Recorded on 1 March 2026",
        "poster": "/media/1000171143-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgZYAltNVAEFJrSfqzt8AA+NDxV4PhS9fvcNjzzqfn7JPyNPXS2zsWmaSMAr0Rkv9GJ0E9rRtIe6GlmwaqF54knRMkx72eyGV7wNZ9HWbeZ1gD5hMceGMuyAAA"
      }
    ]
  },
  {
    "key": "2026-04",
    "label": "April 2026",
    "age": "8 months old",
    "photos": [
      {
        "id": "photo-1000196853-jpg",
        "src": "/media/1000196853-jpg.webp",
        "date": "2026-04-26",
        "caption": "26 April 2026",
        "alt": "Photo from 26 April 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaACw7AxRfkn6yvCgAPY09vWqoMDeBS3DIsN0aQ0MslZKKruVJHYVqsI/rYjs6gPUhCQsTQPvM3qeGHGLiYQ03PHCfXFBPmMdeEUwdpwnngEHjVlM1minow7xt6OGmZgXJy17766gl5fYvQorx94EBUmY0+Ah1XAgvXXPgGhSZj86/egMMXxuytQAAA=="
      },
      {
        "id": "photo-1000197927-jpg",
        "src": "/media/1000197927-jpg.webp",
        "date": "2026-04-28",
        "caption": "28 April 2026",
        "alt": "Photo from 28 April 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCdMoAC8hKcC72vSibDmawAAN4jYLYnEuuvrbngE7y/e9DZ17th0BAzIQ2xn6wr8AuL+SbO84e26Sz4uzQZAvbwAA=="
      }
    ],
    "videos": [
      {
        "id": "video-vid20260413162708",
        "src": "/videos/VID20260413162708.mp4",
        "date": "2026-04-13",
        "title": "April 2026 clip 1",
        "description": "Recorded on 13 April 2026",
        "poster": "/media/1000196853-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaACw7AxRfkn6yvCgAPY09vWqoMDeBS3DIsN0aQ0MslZKKruVJHYVqsI/rYjs6gPUhCQsTQPvM3qeGHGLiYQ03PHCfXFBPmMdeEUwdpwnngEHjVlM1minow7xt6OGmZgXJy17766gl5fYvQorx94EBUmY0+Ah1XAgvXXPgGhSZj86/egMMXxuytQAAA=="
      }
    ]
  },
  {
    "key": "2026-05",
    "label": "May 2026",
    "age": "9 months old",
    "photos": [
      {
        "id": "photo-1000199826-jpg",
        "src": "/media/1000199826-jpg.webp",
        "date": "2026-05-01",
        "caption": "1 May 2026",
        "alt": "Photo from 1 May 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JYwCdABVavmj37NkWGChTAADJOGffKhWrLU+VK+5CKTxEv+HRAo3U1Y3ZXfgFkfQ7okapiQmaqpnvl0F4N77TSt62opYOi3QngDc7wqeTeyjzZ9Dtbo/D+kMaHrLBhZIKh8ootAA="
      },
      {
        "id": "photo-1000208811-jpg",
        "src": "/media/1000208811-jpg.webp",
        "date": "2026-05-12",
        "caption": "12 May 2026",
        "alt": "Photo from 12 May 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JZACdMoACEMgoEwwV3T/AAP653jIH8C/eIjGfr/yJDgvj2nEIRyTPwZ6Z925eo6aSP9fOTvppA73Hb6TlGGLJXDgJgGISLeOmlPYEtioAhHpsTtPcgdzlo8s4eAAA"
      },
      {
        "id": "photo-1000210980-jpg",
        "src": "/media/1000210980-jpg.webp",
        "date": "2026-05-15",
        "caption": "15 May 2026",
        "alt": "Photo from 15 May 2026",
        "width": 1446,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBbdGQBe9LPrVTcHVyPsupUAAP7etTdcPxZRkY/E7ywAyq5hhxgYszrPfKLxnnpyRkFZp8TQS4uXzSr/mSN/CPkwtywra1EqSbwEdjqSG/9Jhror9quPChHa+jp759iKTAwuOFVKx4qohZY4e7+5EFPbdvPUowtJU4gAAAA="
      }
    ],
    "videos": [
      {
        "id": "video-vid-20260510-wa0059",
        "src": "/videos/VID-20260510-WA0059.mp4",
        "date": "2026-05-10",
        "title": "May 2026 clip 1",
        "description": "Recorded on 10 May 2026",
        "poster": "/media/1000199826-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JYwCdABVavmj37NkWGChTAADJOGffKhWrLU+VK+5CKTxEv+HRAo3U1Y3ZXfgFkfQ7okapiQmaqpnvl0F4N77TSt62opYOi3QngDc7wqeTeyjzZ9Dtbo/D+kMaHrLBhZIKh8ootAA="
      }
    ]
  },
  {
    "key": "2026-06",
    "label": "June 2026",
    "age": "10 months old",
    "photos": [
      {
        "id": "photo-1000230149-jpg",
        "src": "/media/1000230149-jpg.webp",
        "date": "2026-06-12",
        "caption": "12 June 2026",
        "alt": "Photo from 12 June 2026",
        "width": 868,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwBACdASoQACMAPu1irE4ppaSiKqwBMB2JZAC7OUAByw/bNjoR9OTjmePuQncOceAA/uv+CRyp7LB3OSzfL4FLH+QfTcm4CUC6gpa0s+ADe0/915PTl9stg0FNDVorlZ7g/eUurmEXh6M1V+IiF0NHCgeSaXhH0lS/6RIucu3v7uxe+n7CmwKgHAOtVIXj/dmy1cFed/r3KTFkrnWZccsdgAA="
      },
      {
        "id": "photo-1000237858-jpg",
        "src": "/media/1000237858-jpg.webp",
        "date": "2026-06-23",
        "caption": "23 June 2026",
        "alt": "Photo from 23 June 2026",
        "width": 868,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAADQBACdASoQACMAPulip02pJaOiNVgIASAdCWwArDlAAbINlYYlFy915/SQFHfmAAD+0o5E1wClZZDZ0OPxSOflKOne5CPvhzkhyARmaeD/lSsu8bs1kWflHdAv6js3lv31i8UrFtFPcvToFHFxz2jy2i7zyX4mS8wKxKsy7fa5EV50F6Y/n9vo6EmCunUrYACKZ5HguY/j24kAMKdAXy6ShylYr2VU7KqhqUAPKAA="
      },
      {
        "id": "photo-1000242025-jpg",
        "src": "/media/1000242025-jpg.webp",
        "date": "2026-06-30",
        "caption": "30 June 2026",
        "alt": "Photo from 30 June 2026",
        "width": 1920,
        "height": 868,
        "span": "normal",
        "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAcAA4BaJQBOgB4keW8uzogA/sqrA4cBj9WGxpzvQL/u1yTcvowuERJgPw9Gu9LQ6u3vbAiz3RYbtUiQbVhpk6wNgEAA"
      }
    ],
    "videos": [
      {
        "id": "video-vid20260605191221",
        "src": "/videos/VID20260605191221.mp4",
        "date": "2026-06-05",
        "title": "June 2026 clip 1",
        "description": "Recorded on 5 June 2026",
        "poster": "/media/1000230149-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwBACdASoQACMAPu1irE4ppaSiKqwBMB2JZAC7OUAByw/bNjoR9OTjmePuQncOceAA/uv+CRyp7LB3OSzfL4FLH+QfTcm4CUC6gpa0s+ADe0/915PTl9stg0FNDVorlZ7g/eUurmEXh6M1V+IiF0NHCgeSaXhH0lS/6RIucu3v7uxe+n7CmwKgHAOtVIXj/dmy1cFed/r3KTFkrnWZccsdgAA="
      },
      {
        "id": "video-vid20260611143011",
        "src": "/videos/VID20260611143011.mp4",
        "date": "2026-06-11",
        "title": "June 2026 clip 2",
        "description": "Recorded on 11 June 2026",
        "poster": "/media/1000237858-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAADQBACdASoQACMAPulip02pJaOiNVgIASAdCWwArDlAAbINlYYlFy915/SQFHfmAAD+0o5E1wClZZDZ0OPxSOflKOne5CPvhzkhyARmaeD/lSsu8bs1kWflHdAv6js3lv31i8UrFtFPcvToFHFxz2jy2i7zyX4mS8wKxKsy7fa5EV50F6Y/n9vo6EmCunUrYACKZ5HguY/j24kAMKdAXy6ShylYr2VU7KqhqUAPKAA="
      }
    ]
  },
  {
    "key": "2026-07",
    "label": "July 2026",
    "age": "11 months old",
    "photos": [
      {
        "id": "photo-1000253373-jpg",
        "src": "/media/1000253373-jpg.webp",
        "date": "2026-07-17",
        "caption": "17 July 2026",
        "alt": "Photo from 17 July 2026",
        "width": 868,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACQBQCdASoQACMAPu1qrVCppaQiqqgBMB2JbACdMoR8noK8xLFYOTSPnfBGwTrN9RDLjPG5AAD+6T/EAug256C2+HKpxGzVodQnDQoaBuULP+ohytm+0musSHpjWLxFX35ZMMb5uSgN2qbf9flVwBhUQV4zanNmYIy0TeMa5RUUfwq5+4hZaRRXCSScSe+M+2QHilFBhXM5fTMmqz2yKRA/9IZG5frwSB7zduUNfgMkaTT6ZfRVxEGj+Bvu/j1djKEMV/wTugAAAA=="
      },
      {
        "id": "photo-1000253985-jpg",
        "src": "/media/1000253985-jpg.webp",
        "date": "2026-07-18",
        "caption": "18 July 2026",
        "alt": "Photo from 18 July 2026",
        "width": 868,
        "height": 1920,
        "span": "tall",
        "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoQACMAPt1Yo02opSMiNUgBEBuJagCuHBR/TaDr7+6qSbS9Jsi+tgAAlp09aJcpbPZur16ETqryqKGRuxXw7wIH72FW/5UruHomXuqXNcbggh8f9GLPBXvu1klqE0BUHAtb5rMwGLdgguEmlc3MhnsproRH29u4Aor9zXQdjjN0AAZkDpDAAA=="
      },
      {
        "id": "photo-1000263580-jpg",
        "src": "/media/1000263580-jpg.webp",
        "date": "2026-07-28",
        "caption": "28 July 2026",
        "alt": "Photo from 28 July 2026",
        "width": 1920,
        "height": 1280,
        "span": "normal",
        "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAsAA4BaJZACdAEZf5rgj9gAAP7zLwO7gBrx8sNjdXMfKlS2xzqwQHxPgLjsX7dMlRQ/SxWywAAA"
      }
    ],
    "videos": [
      {
        "id": "video-vid20260717151541",
        "src": "/videos/VID20260717151541.mp4",
        "date": "2026-07-17",
        "title": "July 2026 clip 1",
        "description": "Recorded on 17 July 2026",
        "poster": "/media/1000253373-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACQBQCdASoQACMAPu1qrVCppaQiqqgBMB2JbACdMoR8noK8xLFYOTSPnfBGwTrN9RDLjPG5AAD+6T/EAug256C2+HKpxGzVodQnDQoaBuULP+ohytm+0musSHpjWLxFX35ZMMb5uSgN2qbf9flVwBhUQV4zanNmYIy0TeMa5RUUfwq5+4hZaRRXCSScSe+M+2QHilFBhXM5fTMmqz2yKRA/9IZG5frwSB7zduUNfgMkaTT6ZfRVxEGj+Bvu/j1djKEMV/wTugAAAA=="
      },
      {
        "id": "video-vid20260718113337",
        "src": "/videos/VID20260718113337.mp4",
        "date": "2026-07-18",
        "title": "July 2026 clip 2",
        "description": "Recorded on 18 July 2026",
        "poster": "/media/1000253985-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoQACMAPt1Yo02opSMiNUgBEBuJagCuHBR/TaDr7+6qSbS9Jsi+tgAAlp09aJcpbPZur16ETqryqKGRuxXw7wIH72FW/5UruHomXuqXNcbggh8f9GLPBXvu1klqE0BUHAtb5rMwGLdgguEmlc3MhnsproRH29u4Aor9zXQdjjN0AAZkDpDAAA=="
      },
      {
        "id": "video-vid20260719122502",
        "src": "/videos/VID20260719122502.mp4",
        "date": "2026-07-19",
        "title": "July 2026 clip 3",
        "description": "Recorded on 19 July 2026",
        "poster": "/media/1000263580-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAsAA4BaJZACdAEZf5rgj9gAAP7zLwO7gBrx8sNjdXMfKlS2xzqwQHxPgLjsX7dMlRQ/SxWywAAA"
      },
      {
        "id": "video-vid20260723204611",
        "src": "/videos/VID20260723204611.mp4",
        "date": "2026-07-23",
        "title": "July 2026 clip 4",
        "description": "Recorded on 23 July 2026",
        "poster": "/media/1000253373-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACQBQCdASoQACMAPu1qrVCppaQiqqgBMB2JbACdMoR8noK8xLFYOTSPnfBGwTrN9RDLjPG5AAD+6T/EAug256C2+HKpxGzVodQnDQoaBuULP+ohytm+0musSHpjWLxFX35ZMMb5uSgN2qbf9flVwBhUQV4zanNmYIy0TeMa5RUUfwq5+4hZaRRXCSScSe+M+2QHilFBhXM5fTMmqz2yKRA/9IZG5frwSB7zduUNfgMkaTT6ZfRVxEGj+Bvu/j1djKEMV/wTugAAAA=="
      },
      {
        "id": "video-vid20260724194713",
        "src": "/videos/VID20260724194713.mp4",
        "date": "2026-07-24",
        "title": "July 2026 clip 5",
        "description": "Recorded on 24 July 2026",
        "poster": "/media/1000253985-jpg.webp",
        "posterBlurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoQACMAPt1Yo02opSMiNUgBEBuJagCuHBR/TaDr7+6qSbS9Jsi+tgAAlp09aJcpbPZur16ETqryqKGRuxXw7wIH72FW/5UruHomXuqXNcbggh8f9GLPBXvu1klqE0BUHAtb5rMwGLdgguEmlc3MhnsproRH29u4Aor9zXQdjjN0AAZkDpDAAA=="
      }
    ]
  }
];

/** Every photo on disk by file name, including ones left out of the gallery. */
export const derivedPhotos: Record<string, DerivedPhoto> = {
  "1000025855.jpg.jpeg": {
    "src": "/media/1000025855-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdMoCGACJQCAbcgLlG1gAAySCBCxWNCL+srF691N7ajrco+SA5Jgs5D8meUS1UOdNPx8vNX9CslqCUPbgHN6lufsBNpZuglmgvyovHZW2/f2aOey/z2j2b0mlbfPIWi7BxI1xMWdmzZAAAAA=="
  },
  "1000027361.jpg.jpeg": {
    "src": "/media/1000027361-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZgCsH8I/+AUAjMx+SUyjWkIAAPkSSl1dLgzEJXw8JCgYJ9Xc98pw3qjp8uezbIYSjmEbkZPbA3scKVv7gn37PdnE6Jep6dbLeSgBdrcVmo+3NCsfw96lnCloJtdVCj7hBqr+LGUHQG1gxSNpWEomozK0fg9tkezOGQAA"
  },
  "1000034978.jpg.jpeg": {
    "src": "/media/1000034978-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoCGACCckjBVRlBoNTPKVUQAAPeza3uQ1J9S8Ao/Bh9lvvJmkRKll2xklU/zwR1J5HDxwWRvEEIzemFJ2caLdmzn7Q1wVx1shQTW/Bk5t3r6a5YP+qm5vtWlqfwJKufPYSImVqC6jJbz1IE2RXtOpiAA"
  },
  "1000041462.jpg.jpeg": {
    "src": "/media/1000041462-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdAB6WV4rv1jBS2t+RD2gA/rsKRJ6ozZXqb3STR7Y8M5ECv4Ifq7O6csbx74m525WK8/ugghDSVP4tOWMHsr7Z3zyP6MK2cFF1ZEuZ438uBv/HkXhm+vcXiHPsisCgzCrAAAA="
  },
  "1000121345.jpg.jpeg": {
    "src": "/media/1000121345-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdMoMpADL+sQI5+VJBo0UAAP7vBC3hLlNx/kvA3kW86tB/Fld1qeNi+BVGCeum4FqAJjzZq7fGJc0hmRlY6BsdT+RJEKMIGLUtG4RkKHKo+rEbAgFUTo4d3bdTYUJNlOkJXghfv3eQQIQKJgYybcMWwYh4AAA="
  },
  "1000140329.jpg.jpeg": {
    "src": "/media/1000140329-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCsABd5oHZW1w934AD+sQIsd2rK4W9ybtO2SR1GNd1mFQeJYf/MlmmrAGzyFZdNtNblL0xvmnHhokx6gQlcY36xJkRY1gaISFI+OzENOXVj/P/7RDv1CNnjAK3IoAA="
  },
  "1000142460.jpg.jpeg": {
    "src": "/media/1000142460-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoMpHY5AKni0/EThO5iAAP4CdigtGX1HJtJ8TIUTNyXupqhvNIB5qbBFaOr6BAa9JadgxDP1nwn7P3E5pxKthB5TI8ZI+W5n9FzlNiJ/6K1g/tOw+4OiezS2WBYcxnu4H++w7TviJz7i2DHZWmeMTFIfx6kCvyh0KgHul/3jvrtjI2heI4t5FaeXeYOLUbNGSYAqoAAA"
  },
  "1000171143.jpg.jpeg": {
    "src": "/media/1000171143-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgZYAltNVAEFJrSfqzt8AA+NDxV4PhS9fvcNjzzqfn7JPyNPXS2zsWmaSMAr0Rkv9GJ0E9rRtIe6GlmwaqF54knRMkx72eyGV7wNZ9HWbeZ1gD5hMceGMuyAAA"
  },
  "1000175489.jpg.jpeg": {
    "src": "/media/1000175489-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQAHOAFYMwCHotxCQpvBHqwAA/hd4O+Z5Bj8MflpZ6cSJR1MKYZOu1Sv9F2jOPyLDKZzM3058UlnlKEFpVzjkc+5P4IDZPzl95wEj5jYNwlgPHd1HFTMmKFG/FYLTXU0vjas9TTAAAA=="
  },
  "1000196853.jpg.jpeg": {
    "src": "/media/1000196853-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaACw7AxRfkn6yvCgAPY09vWqoMDeBS3DIsN0aQ0MslZKKruVJHYVqsI/rYjs6gPUhCQsTQPvM3qeGHGLiYQ03PHCfXFBPmMdeEUwdpwnngEHjVlM1minow7xt6OGmZgXJy17766gl5fYvQorx94EBUmY0+Ah1XAgvXXPgGhSZj86/egMMXxuytQAAA=="
  },
  "1000197927.jpg.jpeg": {
    "src": "/media/1000197927-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCdMoAC8hKcC72vSibDmawAAN4jYLYnEuuvrbngE7y/e9DZ17th0BAzIQ2xn6wr8AuL+SbO84e26Sz4uzQZAvbwAA=="
  },
  "1000199826.jpg.jpeg": {
    "src": "/media/1000199826-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JYwCdABVavmj37NkWGChTAADJOGffKhWrLU+VK+5CKTxEv+HRAo3U1Y3ZXfgFkfQ7okapiQmaqpnvl0F4N77TSt62opYOi3QngDc7wqeTeyjzZ9Dtbo/D+kMaHrLBhZIKh8ootAA="
  },
  "1000199827.jpg.jpeg": {
    "src": "/media/1000199827-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdABeL+vHwaK7XqAD9IpHo0rHqI4cfXZ3ELhGLThCyAQdniLO9n9hjkG1LJrTvS1joTBOM6mlzePhUWHEOt954AY1c3Y0dqen3wDuNp854L5uKJ1tiWBEHEwYt7Nb5Yb3mLQAAAA=="
  },
  "1000208811.jpg.jpeg": {
    "src": "/media/1000208811-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JZACdMoACEMgoEwwV3T/AAP653jIH8C/eIjGfr/yJDgvj2nEIRyTPwZ6Z925eo6aSP9fOTvppA73Hb6TlGGLJXDgJgGISLeOmlPYEtioAhHpsTtPcgdzlo8s4eAAA"
  },
  "1000210980.jpg.jpeg": {
    "src": "/media/1000210980-jpg.webp",
    "width": 1446,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBbdGQBe9LPrVTcHVyPsupUAAP7etTdcPxZRkY/E7ywAyq5hhxgYszrPfKLxnnpyRkFZp8TQS4uXzSr/mSN/CPkwtywra1EqSbwEdjqSG/9Jhror9quPChHa+jp759iKTAwuOFVKx4qohZY4e7+5EFPbdvPUowtJU4gAAAA="
  },
  "1000230149.jpg.jpeg": {
    "src": "/media/1000230149-jpg.webp",
    "width": 868,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwBACdASoQACMAPu1irE4ppaSiKqwBMB2JZAC7OUAByw/bNjoR9OTjmePuQncOceAA/uv+CRyp7LB3OSzfL4FLH+QfTcm4CUC6gpa0s+ADe0/915PTl9stg0FNDVorlZ7g/eUurmEXh6M1V+IiF0NHCgeSaXhH0lS/6RIucu3v7uxe+n7CmwKgHAOtVIXj/dmy1cFed/r3KTFkrnWZccsdgAA="
  },
  "1000237858.jpg.jpeg": {
    "src": "/media/1000237858-jpg.webp",
    "width": 868,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAADQBACdASoQACMAPulip02pJaOiNVgIASAdCWwArDlAAbINlYYlFy915/SQFHfmAAD+0o5E1wClZZDZ0OPxSOflKOne5CPvhzkhyARmaeD/lSsu8bs1kWflHdAv6js3lv31i8UrFtFPcvToFHFxz2jy2i7zyX4mS8wKxKsy7fa5EV50F6Y/n9vo6EmCunUrYACKZ5HguY/j24kAMKdAXy6ShylYr2VU7KqhqUAPKAA="
  },
  "1000242025.jpg.jpeg": {
    "src": "/media/1000242025-jpg.webp",
    "width": 1920,
    "height": 868,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAcAA4BaJQBOgB4keW8uzogA/sqrA4cBj9WGxpzvQL/u1yTcvowuERJgPw9Gu9LQ6u3vbAiz3RYbtUiQbVhpk6wNgEAA"
  },
  "1000253373.jpg.jpeg": {
    "src": "/media/1000253373-jpg.webp",
    "width": 868,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACQBQCdASoQACMAPu1qrVCppaQiqqgBMB2JbACdMoR8noK8xLFYOTSPnfBGwTrN9RDLjPG5AAD+6T/EAug256C2+HKpxGzVodQnDQoaBuULP+ohytm+0musSHpjWLxFX35ZMMb5uSgN2qbf9flVwBhUQV4zanNmYIy0TeMa5RUUfwq5+4hZaRRXCSScSe+M+2QHilFBhXM5fTMmqz2yKRA/9IZG5frwSB7zduUNfgMkaTT6ZfRVxEGj+Bvu/j1djKEMV/wTugAAAA=="
  },
  "1000253985.jpg.jpeg": {
    "src": "/media/1000253985-jpg.webp",
    "width": 868,
    "height": 1920,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoQACMAPt1Yo02opSMiNUgBEBuJagCuHBR/TaDr7+6qSbS9Jsi+tgAAlp09aJcpbPZur16ETqryqKGRuxXw7wIH72FW/5UruHomXuqXNcbggh8f9GLPBXvu1klqE0BUHAtb5rMwGLdgguEmlc3MhnsproRH29u4Aor9zXQdjjN0AAZkDpDAAA=="
  },
  "1000263580.jpg.jpeg": {
    "src": "/media/1000263580-jpg.webp",
    "width": 1920,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAsAA4BaJZACdAEZf5rgj9gAAP7zLwO7gBrx8sNjdXMfKlS2xzqwQHxPgLjsX7dMlRQ/SxWywAAA"
  },
  "1000263596.jpg.jpeg": {
    "src": "/media/1000263596-jpg.webp",
    "width": 1920,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAsAA4BaJZgCdAD6+0aXAAD+8VROGyMeyGe7ENljFQTIDvIux3lzJdh9ErMxkYMK9xObZzgzEgAA"
  },
  "IMG-20260819-123149.jpeg": {
    "src": "/media/img-20260819-123149.webp",
    "width": 864,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZACdABEkkN3F/Qe3AAD2sI4bb4otNmDF3dFV3Tk2dZEiGS1i522k5xXPGIrb5sg8nojESKaSnzbFVanEdNf0gOdmjbpoaRW3DpejkfxjJK8r1Or/qu4PhZZU7CU4Fwq/n+1+n/LwTD/Yrol6p83W2qe/rkNZQbcNiWUCcm8B+4ZXJEfO5cQA"
  },
  "IMG-20260819-123157.jpeg": {
    "src": "/media/img-20260819-123157.webp",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoR3AdCtDHduxrnImVw0AAD+w5Xm7g8AJnBA6yMGt/K6YJVwxlZ4yxlKKVJkB6c16aYpkt8Eo9+X9AOHvcYiToTq2dj5Fp/i6mE1bqQzxDg0QW63gdLAea4aoc/o33EkFENj/ffn6JBbxL1x9QkevoTFeb9LklTm+AR1zVcTep9TVRVOEJZSkWuAAAA="
  }
};
